[package]
name = "actix-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.1.4", features = ["postgres", "r2d2"] }
r2d2 = "0.8.10"
serde = { version = "1.0.137", features = ["derive"] }

